# Generated by Django 5.1.4 on 2024-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseid', models.AutoField(primary_key=True, serialize=False)),
                ('expensename', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
